import { build } from "esbuild-wasm"
import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const result = await build({
  entryPoints: [resolve(root, "src/ui/galaxy/app.ts")],
  bundle: true,
  write: false,
  outdir: resolve(root, ".ui-build"),
  format: "iife",
  platform: "browser",
  target: "es2020",
  loader: { ".css": "css" },
})
const js = result.outputFiles.find((file) => file.path.endsWith(".js"))?.text
const css = result.outputFiles.find((file) => file.path.endsWith(".css"))?.text ?? ""
if (!js) throw new Error("Could not build Requirement Galaxy JavaScript")
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><div id="app"></div><script>${js}</script></body></html>`
const out = resolve(root, "src/ui/galaxy/galaxyApp.generated.ts")
writeFileSync(out, `// AUTO-GENERATED by scripts/build-ui.mjs — DO NOT EDIT.\nexport const GALAXY_APP_HTML = ${JSON.stringify(html)}\n`)
console.log(`build-ui: Requirement Galaxy → ${out}`)
