// Typed access to the tool descriptions authored in each src/features/<name>/prompt.md and embedded
// at build time by scripts/embed-docs.mjs. Tool files never carry their own description string:
// registerTool.ts resolves it from the tool name, so the prompt and the registration can't drift.
//
// No completeness check is needed here for ToolName the way there is for StepType below: TOOL_NAMES
// and TOOL_DESCRIPTIONS are both generated by embed-docs.mjs from the very same src/features/ folder
// listing, so their key sets are identical by construction — there is no second, hand-maintained list
// they could drift from.

import { COLUMN_MEANINGS, TOOL_DESCRIPTIONS, type ToolName } from "./index.generated.js"
import type { StepType } from "../shared/traceability/dto.js"

export function toolDescription(name: ToolName): string {
  return TOOL_DESCRIPTIONS[name]
}

// What each traceability column type MEANS, from the `## STEP_TYPE` sections of
// src/shared/traceability/prompts/matrix_columns.md. Unlike ToolName above, StepType is a
// hand-maintained enum (shared/traceability/dto.ts) that this glossary is NOT generated from, so it
// genuinely can drift — hence the completeness check, enforced in BOTH directions at compile time: a
// step type with no section fails this assignment, a section matching no step type fails the alias
// below. So the glossary cannot silently fall behind the enum — which is the whole point, since a
// type the model cannot interpret is a column it will refuse to use.
//
// (Importing a type from shared/ here mirrors the ToolName import above: prompts/ owns text but is
// allowed to check itself against the enums that text describes.)
const MEANINGS: Record<StepType, string> = COLUMN_MEANINGS
type AssertExtends<Subset extends Superset, Superset> = Subset
type _NoOrphanColumn = AssertExtends<keyof typeof COLUMN_MEANINGS, StepType>

export function columnMeaning(type: StepType): string {
  return MEANINGS[type]
}
